# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: register.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregister.proto\"\x1c\n\x0cHeartBeatMsg\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x0cHeartBeatRsp\x12\x0e\n\x06status\x18\x01 \x01(\x05\"$\n\x07UserMsg\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03pwd\x18\x02 \x01(\t\"\x19\n\x07UserRsp\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\'\n\nRoomPlayer\x12\x0b\n\x03pos\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\'\n\x07RoomMsg\x12\x0e\n\x06roomID\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"5\n\x0cJoinRoomResp\x12\x0b\n\x03pos\x18\x01 \x01(\x05\x12\x18\n\x03\x61ll\x18\x02 \x03(\x0b\x32\x0b.RoomPlayer\"\x1f\n\rLeaveRoomResp\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\xd3\x01\n\x08Register\x12\x1f\n\x07UserReg\x12\x08.UserMsg\x1a\x08.UserRsp\"\x00\x12+\n\tHeartBeat\x12\r.HeartBeatMsg\x1a\r.HeartBeatRsp\"\x00\x12%\n\x08joinRoom\x12\x08.RoomMsg\x1a\r.JoinRoomResp\"\x00\x12\'\n\tleaveRoom\x12\x08.RoomMsg\x1a\x0e.LeaveRoomResp\"\x00\x12)\n\tchangePos\x12\x0b.RoomPlayer\x1a\r.JoinRoomResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'register_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEATMSG']._serialized_start=18
  _globals['_HEARTBEATMSG']._serialized_end=46
  _globals['_HEARTBEATRSP']._serialized_start=48
  _globals['_HEARTBEATRSP']._serialized_end=78
  _globals['_USERMSG']._serialized_start=80
  _globals['_USERMSG']._serialized_end=116
  _globals['_USERRSP']._serialized_start=118
  _globals['_USERRSP']._serialized_end=143
  _globals['_ROOMPLAYER']._serialized_start=145
  _globals['_ROOMPLAYER']._serialized_end=184
  _globals['_ROOMMSG']._serialized_start=186
  _globals['_ROOMMSG']._serialized_end=225
  _globals['_JOINROOMRESP']._serialized_start=227
  _globals['_JOINROOMRESP']._serialized_end=280
  _globals['_LEAVEROOMRESP']._serialized_start=282
  _globals['_LEAVEROOMRESP']._serialized_end=313
  _globals['_REGISTER']._serialized_start=316
  _globals['_REGISTER']._serialized_end=527
# @@protoc_insertion_point(module_scope)
