# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import register_pb2 as register__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in register_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RegisterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserReg = channel.unary_unary(
                '/Register/UserReg',
                request_serializer=register__pb2.UserMsg.SerializeToString,
                response_deserializer=register__pb2.UserRsp.FromString,
                _registered_method=True)
        self.HeartBeat = channel.unary_unary(
                '/Register/HeartBeat',
                request_serializer=register__pb2.HeartBeatMsg.SerializeToString,
                response_deserializer=register__pb2.HeartBeatRsp.FromString,
                _registered_method=True)
        self.joinRoom = channel.unary_unary(
                '/Register/joinRoom',
                request_serializer=register__pb2.RoomMsg.SerializeToString,
                response_deserializer=register__pb2.JoinRoomResp.FromString,
                _registered_method=True)
        self.leaveRoom = channel.unary_unary(
                '/Register/leaveRoom',
                request_serializer=register__pb2.RoomMsg.SerializeToString,
                response_deserializer=register__pb2.LeaveRoomResp.FromString,
                _registered_method=True)
        self.changePos = channel.unary_unary(
                '/Register/changePos',
                request_serializer=register__pb2.RoomPlayer.SerializeToString,
                response_deserializer=register__pb2.JoinRoomResp.FromString,
                _registered_method=True)


class RegisterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UserReg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartBeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def joinRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def leaveRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def changePos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegisterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UserReg': grpc.unary_unary_rpc_method_handler(
                    servicer.UserReg,
                    request_deserializer=register__pb2.UserMsg.FromString,
                    response_serializer=register__pb2.UserRsp.SerializeToString,
            ),
            'HeartBeat': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartBeat,
                    request_deserializer=register__pb2.HeartBeatMsg.FromString,
                    response_serializer=register__pb2.HeartBeatRsp.SerializeToString,
            ),
            'joinRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.joinRoom,
                    request_deserializer=register__pb2.RoomMsg.FromString,
                    response_serializer=register__pb2.JoinRoomResp.SerializeToString,
            ),
            'leaveRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.leaveRoom,
                    request_deserializer=register__pb2.RoomMsg.FromString,
                    response_serializer=register__pb2.LeaveRoomResp.SerializeToString,
            ),
            'changePos': grpc.unary_unary_rpc_method_handler(
                    servicer.changePos,
                    request_deserializer=register__pb2.RoomPlayer.FromString,
                    response_serializer=register__pb2.JoinRoomResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Register', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Register', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Register(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UserReg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Register/UserReg',
            register__pb2.UserMsg.SerializeToString,
            register__pb2.UserRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartBeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Register/HeartBeat',
            register__pb2.HeartBeatMsg.SerializeToString,
            register__pb2.HeartBeatRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def joinRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Register/joinRoom',
            register__pb2.RoomMsg.SerializeToString,
            register__pb2.JoinRoomResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def leaveRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Register/leaveRoom',
            register__pb2.RoomMsg.SerializeToString,
            register__pb2.LeaveRoomResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def changePos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Register/changePos',
            register__pb2.RoomPlayer.SerializeToString,
            register__pb2.JoinRoomResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
