// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: game.proto
#ifndef GRPC_game_2eproto__INCLUDED
#define GRPC_game_2eproto__INCLUDED

#include "game.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

// 服务端给客户端发牌, 客户端作为server接受消息
class Poker final {
 public:
  static constexpr char const* service_full_name() {
    return "Poker";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Licensing(::grpc::ClientContext* context, const ::PokerRequest& request, ::PokerResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PokerResp>> AsyncLicensing(::grpc::ClientContext* context, const ::PokerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PokerResp>>(AsyncLicensingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PokerResp>> PrepareAsyncLicensing(::grpc::ClientContext* context, const ::PokerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PokerResp>>(PrepareAsyncLicensingRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Licensing(::grpc::ClientContext* context, const ::PokerRequest* request, ::PokerResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Licensing(::grpc::ClientContext* context, const ::PokerRequest* request, ::PokerResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PokerResp>* AsyncLicensingRaw(::grpc::ClientContext* context, const ::PokerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PokerResp>* PrepareAsyncLicensingRaw(::grpc::ClientContext* context, const ::PokerRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Licensing(::grpc::ClientContext* context, const ::PokerRequest& request, ::PokerResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PokerResp>> AsyncLicensing(::grpc::ClientContext* context, const ::PokerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PokerResp>>(AsyncLicensingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PokerResp>> PrepareAsyncLicensing(::grpc::ClientContext* context, const ::PokerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PokerResp>>(PrepareAsyncLicensingRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Licensing(::grpc::ClientContext* context, const ::PokerRequest* request, ::PokerResp* response, std::function<void(::grpc::Status)>) override;
      void Licensing(::grpc::ClientContext* context, const ::PokerRequest* request, ::PokerResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::PokerResp>* AsyncLicensingRaw(::grpc::ClientContext* context, const ::PokerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::PokerResp>* PrepareAsyncLicensingRaw(::grpc::ClientContext* context, const ::PokerRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Licensing_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Licensing(::grpc::ServerContext* context, const ::PokerRequest* request, ::PokerResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Licensing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Licensing() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Licensing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Licensing(::grpc::ServerContext* /*context*/, const ::PokerRequest* /*request*/, ::PokerResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLicensing(::grpc::ServerContext* context, ::PokerRequest* request, ::grpc::ServerAsyncResponseWriter< ::PokerResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Licensing<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Licensing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Licensing() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::PokerRequest, ::PokerResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::PokerRequest* request, ::PokerResp* response) { return this->Licensing(context, request, response); }));}
    void SetMessageAllocatorFor_Licensing(
        ::grpc::MessageAllocator< ::PokerRequest, ::PokerResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::PokerRequest, ::PokerResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Licensing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Licensing(::grpc::ServerContext* /*context*/, const ::PokerRequest* /*request*/, ::PokerResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Licensing(
      ::grpc::CallbackServerContext* /*context*/, const ::PokerRequest* /*request*/, ::PokerResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Licensing<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Licensing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Licensing() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Licensing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Licensing(::grpc::ServerContext* /*context*/, const ::PokerRequest* /*request*/, ::PokerResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Licensing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Licensing() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Licensing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Licensing(::grpc::ServerContext* /*context*/, const ::PokerRequest* /*request*/, ::PokerResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLicensing(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Licensing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Licensing() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Licensing(context, request, response); }));
    }
    ~WithRawCallbackMethod_Licensing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Licensing(::grpc::ServerContext* /*context*/, const ::PokerRequest* /*request*/, ::PokerResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Licensing(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Licensing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Licensing() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::PokerRequest, ::PokerResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::PokerRequest, ::PokerResp>* streamer) {
                       return this->StreamedLicensing(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Licensing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Licensing(::grpc::ServerContext* /*context*/, const ::PokerRequest* /*request*/, ::PokerResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLicensing(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::PokerRequest,::PokerResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Licensing<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Licensing<Service > StreamedService;
};


#endif  // GRPC_game_2eproto__INCLUDED
