// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto
// Protobuf C++ Version: 5.26.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_game_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_game_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_game_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_game_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_game_2eproto;
class PokerRequest;
struct PokerRequestDefaultTypeInternal;
extern PokerRequestDefaultTypeInternal _PokerRequest_default_instance_;
class PokerResp;
struct PokerRespDefaultTypeInternal;
extern PokerRespDefaultTypeInternal _PokerResp_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class PokerResp final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PokerResp) */ {
 public:
  inline PokerResp() : PokerResp(nullptr) {}
  ~PokerResp() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PokerResp(
      ::google::protobuf::internal::ConstantInitialized);

  inline PokerResp(const PokerResp& from) : PokerResp(nullptr, from) {}
  inline PokerResp(PokerResp&& from) noexcept
      : PokerResp(nullptr, std::move(from)) {}
  inline PokerResp& operator=(const PokerResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline PokerResp& operator=(PokerResp&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PokerResp& default_instance() {
    return *internal_default_instance();
  }
  static inline const PokerResp* internal_default_instance() {
    return reinterpret_cast<const PokerResp*>(
        &_PokerResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PokerResp& a, PokerResp& b) { a.Swap(&b); }
  inline void Swap(PokerResp* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PokerResp* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PokerResp* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<PokerResp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PokerResp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PokerResp& from) { PokerResp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(PokerResp* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "PokerResp"; }

 protected:
  explicit PokerResp(::google::protobuf::Arena* arena);
  PokerResp(::google::protobuf::Arena* arena, const PokerResp& from);
  PokerResp(::google::protobuf::Arena* arena, PokerResp&& from) noexcept
      : PokerResp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
  };
  // int32 status = 1;
  void clear_status() ;
  ::int32_t status() const;
  void set_status(::int32_t value);

  private:
  ::int32_t _internal_status() const;
  void _internal_set_status(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:PokerResp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::int32_t status_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class PokerRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PokerRequest) */ {
 public:
  inline PokerRequest() : PokerRequest(nullptr) {}
  ~PokerRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PokerRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline PokerRequest(const PokerRequest& from) : PokerRequest(nullptr, from) {}
  inline PokerRequest(PokerRequest&& from) noexcept
      : PokerRequest(nullptr, std::move(from)) {}
  inline PokerRequest& operator=(const PokerRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PokerRequest& operator=(PokerRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PokerRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const PokerRequest* internal_default_instance() {
    return reinterpret_cast<const PokerRequest*>(
        &_PokerRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PokerRequest& a, PokerRequest& b) { a.Swap(&b); }
  inline void Swap(PokerRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PokerRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PokerRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<PokerRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PokerRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PokerRequest& from) { PokerRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(PokerRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "PokerRequest"; }

 protected:
  explicit PokerRequest(::google::protobuf::Arena* arena);
  PokerRequest(::google::protobuf::Arena* arena, const PokerRequest& from);
  PokerRequest(::google::protobuf::Arena* arena, PokerRequest&& from) noexcept
      : PokerRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSuitFieldNumber = 1,
    kPointFieldNumber = 2,
  };
  // string suit = 1;
  void clear_suit() ;
  const std::string& suit() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_suit(Arg_&& arg, Args_... args);
  std::string* mutable_suit();
  PROTOBUF_NODISCARD std::string* release_suit();
  void set_allocated_suit(std::string* value);

  private:
  const std::string& _internal_suit() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_suit(
      const std::string& value);
  std::string* _internal_mutable_suit();

  public:
  // int32 point = 2;
  void clear_point() ;
  ::int32_t point() const;
  void set_point(::int32_t value);

  private:
  ::int32_t _internal_point() const;
  void _internal_set_point(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:PokerRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      25, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr suit_;
    ::int32_t point_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PokerRequest

// string suit = 1;
inline void PokerRequest::clear_suit() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.suit_.ClearToEmpty();
}
inline const std::string& PokerRequest::suit() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PokerRequest.suit)
  return _internal_suit();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void PokerRequest::set_suit(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.suit_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PokerRequest.suit)
}
inline std::string* PokerRequest::mutable_suit() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_suit();
  // @@protoc_insertion_point(field_mutable:PokerRequest.suit)
  return _s;
}
inline const std::string& PokerRequest::_internal_suit() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.suit_.Get();
}
inline void PokerRequest::_internal_set_suit(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.suit_.Set(value, GetArena());
}
inline std::string* PokerRequest::_internal_mutable_suit() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.suit_.Mutable( GetArena());
}
inline std::string* PokerRequest::release_suit() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:PokerRequest.suit)
  return _impl_.suit_.Release();
}
inline void PokerRequest::set_allocated_suit(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.suit_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.suit_.IsDefault()) {
          _impl_.suit_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PokerRequest.suit)
}

// int32 point = 2;
inline void PokerRequest::clear_point() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.point_ = 0;
}
inline ::int32_t PokerRequest::point() const {
  // @@protoc_insertion_point(field_get:PokerRequest.point)
  return _internal_point();
}
inline void PokerRequest::set_point(::int32_t value) {
  _internal_set_point(value);
  // @@protoc_insertion_point(field_set:PokerRequest.point)
}
inline ::int32_t PokerRequest::_internal_point() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.point_;
}
inline void PokerRequest::_internal_set_point(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.point_ = value;
}

// -------------------------------------------------------------------

// PokerResp

// int32 status = 1;
inline void PokerResp::clear_status() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.status_ = 0;
}
inline ::int32_t PokerResp::status() const {
  // @@protoc_insertion_point(field_get:PokerResp.status)
  return _internal_status();
}
inline void PokerResp::set_status(::int32_t value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:PokerResp.status)
}
inline ::int32_t PokerResp::_internal_status() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.status_;
}
inline void PokerResp::_internal_set_status(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.status_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_game_2eproto_2epb_2eh
