// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: game.proto

#include "game.pb.h"
#include "game.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* Poker_method_names[] = {
  "/Poker/Licensing",
};

std::unique_ptr< Poker::Stub> Poker::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Poker::Stub> stub(new Poker::Stub(channel, options));
  return stub;
}

Poker::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Licensing_(Poker_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Poker::Stub::Licensing(::grpc::ClientContext* context, const ::PokerRequest& request, ::PokerResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::PokerRequest, ::PokerResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Licensing_, context, request, response);
}

void Poker::Stub::async::Licensing(::grpc::ClientContext* context, const ::PokerRequest* request, ::PokerResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::PokerRequest, ::PokerResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Licensing_, context, request, response, std::move(f));
}

void Poker::Stub::async::Licensing(::grpc::ClientContext* context, const ::PokerRequest* request, ::PokerResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Licensing_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::PokerResp>* Poker::Stub::PrepareAsyncLicensingRaw(::grpc::ClientContext* context, const ::PokerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::PokerResp, ::PokerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Licensing_, context, request);
}

::grpc::ClientAsyncResponseReader< ::PokerResp>* Poker::Stub::AsyncLicensingRaw(::grpc::ClientContext* context, const ::PokerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLicensingRaw(context, request, cq);
  result->StartCall();
  return result;
}

Poker::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Poker_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Poker::Service, ::PokerRequest, ::PokerResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Poker::Service* service,
             ::grpc::ServerContext* ctx,
             const ::PokerRequest* req,
             ::PokerResp* resp) {
               return service->Licensing(ctx, req, resp);
             }, this)));
}

Poker::Service::~Service() {
}

::grpc::Status Poker::Service::Licensing(::grpc::ServerContext* context, const ::PokerRequest* request, ::PokerResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


