// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto
// Protobuf C++ Version: 5.26.1

#include "game.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr PokerResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : status_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PokerResp::PokerResp(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PokerRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PokerRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PokerRespDefaultTypeInternal() {}
  union {
    PokerResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PokerRespDefaultTypeInternal _PokerResp_default_instance_;

inline constexpr PokerRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : suit_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        point_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PokerRequest::PokerRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PokerRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PokerRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PokerRequestDefaultTypeInternal() {}
  union {
    PokerRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PokerRequestDefaultTypeInternal _PokerRequest_default_instance_;
static ::_pb::Metadata file_level_metadata_game_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_game_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_game_2eproto = nullptr;
const ::uint32_t
    TableStruct_game_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::PokerRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::PokerRequest, _impl_.suit_),
        PROTOBUF_FIELD_OFFSET(::PokerRequest, _impl_.point_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::PokerResp, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::PokerResp, _impl_.status_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::PokerRequest)},
        {10, -1, -1, sizeof(::PokerResp)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_PokerRequest_default_instance_._instance,
    &::_PokerResp_default_instance_._instance,
};
const char descriptor_table_protodef_game_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\ngame.proto\"+\n\014PokerRequest\022\014\n\004suit\030\001 \001"
    "(\t\022\r\n\005point\030\002 \001(\005\"\033\n\tPokerResp\022\016\n\006status"
    "\030\001 \001(\00521\n\005Poker\022(\n\tLicensing\022\r.PokerRequ"
    "est\032\n.PokerResp\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_game_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_game_2eproto = {
    false,
    false,
    145,
    descriptor_table_protodef_game_2eproto,
    "game.proto",
    &descriptor_table_game_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_game_2eproto::offsets,
    file_level_metadata_game_2eproto,
    file_level_enum_descriptors_game_2eproto,
    file_level_service_descriptors_game_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_game_2eproto_getter() {
  return &descriptor_table_game_2eproto;
}
// ===================================================================

class PokerRequest::_Internal {
 public:
};

PokerRequest::PokerRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PokerRequest)
}
inline PROTOBUF_NDEBUG_INLINE PokerRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : suit_(arena, from.suit_),
        _cached_size_{0} {}

PokerRequest::PokerRequest(
    ::google::protobuf::Arena* arena,
    const PokerRequest& from)
    : ::google::protobuf::Message(arena) {
  PokerRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.point_ = from._impl_.point_;

  // @@protoc_insertion_point(copy_constructor:PokerRequest)
}
inline PROTOBUF_NDEBUG_INLINE PokerRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : suit_(arena),
        _cached_size_{0} {}

inline void PokerRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.point_ = {};
}
PokerRequest::~PokerRequest() {
  // @@protoc_insertion_point(destructor:PokerRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PokerRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.suit_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
PokerRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(PokerRequest, _impl_._cached_size_),
              false,
          },
          &PokerRequest::MergeImpl,
          &PokerRequest::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void PokerRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:PokerRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.suit_.ClearToEmpty();
  _impl_.point_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PokerRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 25, 2> PokerRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PokerRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::PokerRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 point = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PokerRequest, _impl_.point_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(PokerRequest, _impl_.point_)}},
    // string suit = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PokerRequest, _impl_.suit_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string suit = 1;
    {PROTOBUF_FIELD_OFFSET(PokerRequest, _impl_.suit_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 point = 2;
    {PROTOBUF_FIELD_OFFSET(PokerRequest, _impl_.point_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\14\4\0\0\0\0\0\0"
    "PokerRequest"
    "suit"
  }},
};

::uint8_t* PokerRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PokerRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string suit = 1;
  if (!this->_internal_suit().empty()) {
    const std::string& _s = this->_internal_suit();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PokerRequest.suit");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int32 point = 2;
  if (this->_internal_point() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_point(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PokerRequest)
  return target;
}

::size_t PokerRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PokerRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string suit = 1;
  if (!this->_internal_suit().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_suit());
  }

  // int32 point = 2;
  if (this->_internal_point() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_point());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void PokerRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PokerRequest*>(&to_msg);
  auto& from = static_cast<const PokerRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PokerRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_suit().empty()) {
    _this->_internal_set_suit(from._internal_suit());
  }
  if (from._internal_point() != 0) {
    _this->_impl_.point_ = from._impl_.point_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PokerRequest::CopyFrom(const PokerRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PokerRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PokerRequest::IsInitialized() const {
  return true;
}

void PokerRequest::InternalSwap(PokerRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.suit_, &other->_impl_.suit_, arena);
        swap(_impl_.point_, other->_impl_.point_);
}

::google::protobuf::Metadata PokerRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_game_2eproto_getter,
                                   &descriptor_table_game_2eproto_once,
                                   file_level_metadata_game_2eproto[0]);
}
// ===================================================================

class PokerResp::_Internal {
 public:
};

PokerResp::PokerResp(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PokerResp)
}
PokerResp::PokerResp(
    ::google::protobuf::Arena* arena, const PokerResp& from)
    : PokerResp(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE PokerResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void PokerResp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
PokerResp::~PokerResp() {
  // @@protoc_insertion_point(destructor:PokerResp)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PokerResp::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
PokerResp::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(PokerResp, _impl_._cached_size_),
              false,
          },
          &PokerResp::MergeImpl,
          &PokerResp::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void PokerResp::Clear() {
// @@protoc_insertion_point(message_clear_start:PokerResp)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PokerResp::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> PokerResp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PokerResp_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::PokerResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PokerResp, _impl_.status_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PokerResp, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 status = 1;
    {PROTOBUF_FIELD_OFFSET(PokerResp, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* PokerResp::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PokerResp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 status = 1;
  if (this->_internal_status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_status(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PokerResp)
  return target;
}

::size_t PokerResp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PokerResp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 status = 1;
  if (this->_internal_status() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void PokerResp::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PokerResp*>(&to_msg);
  auto& from = static_cast<const PokerResp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PokerResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_status() != 0) {
    _this->_impl_.status_ = from._impl_.status_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PokerResp::CopyFrom(const PokerResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PokerResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PokerResp::IsInitialized() const {
  return true;
}

void PokerResp::InternalSwap(PokerResp* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata PokerResp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_game_2eproto_getter,
                                   &descriptor_table_game_2eproto_once,
                                   file_level_metadata_game_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_game_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
